### ISSUE TITLE
Can't build this

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-engine#2]
I tried the instructions and got this:

```
make setup
go get -u \
		github.com/Masterminds/glide \
		gopkg.in/alecthomas/gometalinter.v2 \
		github.com/onsi/ginkgo/ginkgo
glide install
make: glide: No such file or directory
make: *** [setup] Error 1
```

Any ideas? Can you set up CI?

**Comment by aslakhellesoy** [comment]
I assume I just need to define `$GOPATH` - I'm just starting my Go journey.

Let's make it easy to stand up for people who don't know the first thing about Go :-)

**Comment by aslakhellesoy** [comment]
Just saw you have set up CI - maybe add a banner in README :-)

**Comment by charlierudolph** [comment]
Auhh. You need to add `$GOPATH/bin` to your path, I'll add a note about that.

**Comment by charlierudolph** [comment]
Can you please review the current [CONTRIBUTING.md](https://github.com/cucumber/cucumber-pickle-runner/blob/cf1757ac71b7b13dce6848a96ec5eab350b56bcf/CONTRIBUTING.md)?

**Comment by charlierudolph** [comment]
@aslakhellesoy have you been able to build this? I just got it working again after the rename

**Comment by aslakhellesoy** [comment]
I get this error with `make spec`:

```
make spec
go install
main.go:3:8: cannot find package "github.com/cucumber/cucumber-engine" in any of:
	/usr/local/Cellar/go/1.10.3/libexec/src/github.com/cucumber/cucumber-engine (from $GOROOT)
	/Users/aslakhellesoy/go/src/github.com/cucumber/cucumber-engine (from $GOPATH)
make: *** [build] Error 1
```

My `GOPATH=/Users/aslakhellesoy/go`
I tried `ln -s $(pwd) ${GOPATH}/src/github.com/cucumber/cucumber-engine`, but then got this error:

```
make spec
go install
main.go:3:8: import "github.com/cucumber/cucumber-engine" is a program, not an importable package
make: *** [build] Error 1
```

I removed the symlink. Are there any other steps I'm missing?

**Comment by aslakhellesoy** [comment]
I got it to build! I missed that I had to clone it into the `${GOPATH}/src/github.com/cucumber/cucumber-engine` directory :-)
